name = "personal"
main = "dist/_worker.js/index.js"
compatibility_date = "2022-05-10"
pages_build_output_dir = "./dist"

[site]
bucket = './dist'

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "personal"
database_id = "98d057a5-dc46-4907-af15-a6bc672bc7da"
